[project]
name = 'Blockchain-Based-Hotel-Reservation-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.inventory-management]
path = 'contracts/inventory-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.payment-processing]
path = 'contracts/payment-processing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
